/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ProductCarousel {
    }
    interface ProductItem {
        "desc": string;
        "i": number;
        "name": string;
        "price": number;
        "src": string;
    }
    interface ProductText {
        "desc": string;
        "i": number;
        "price": number;
    }
}
export interface ProductTextCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLProductTextElement;
}
declare global {
    interface HTMLProductCarouselElement extends Components.ProductCarousel, HTMLStencilElement {
    }
    var HTMLProductCarouselElement: {
        prototype: HTMLProductCarouselElement;
        new (): HTMLProductCarouselElement;
    };
    interface HTMLProductItemElement extends Components.ProductItem, HTMLStencilElement {
    }
    var HTMLProductItemElement: {
        prototype: HTMLProductItemElement;
        new (): HTMLProductItemElement;
    };
    interface HTMLProductTextElement extends Components.ProductText, HTMLStencilElement {
    }
    var HTMLProductTextElement: {
        prototype: HTMLProductTextElement;
        new (): HTMLProductTextElement;
    };
    interface HTMLElementTagNameMap {
        "product-carousel": HTMLProductCarouselElement;
        "product-item": HTMLProductItemElement;
        "product-text": HTMLProductTextElement;
    }
}
declare namespace LocalJSX {
    interface ProductCarousel {
    }
    interface ProductItem {
        "desc"?: string;
        "i"?: number;
        "name"?: string;
        "price"?: number;
        "src"?: string;
    }
    interface ProductText {
        "desc"?: string;
        "i"?: number;
        "onCartChange"?: (event: ProductTextCustomEvent<any[]>) => void;
        "price"?: number;
    }
    interface IntrinsicElements {
        "product-carousel": ProductCarousel;
        "product-item": ProductItem;
        "product-text": ProductText;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "product-carousel": LocalJSX.ProductCarousel & JSXBase.HTMLAttributes<HTMLProductCarouselElement>;
            "product-item": LocalJSX.ProductItem & JSXBase.HTMLAttributes<HTMLProductItemElement>;
            "product-text": LocalJSX.ProductText & JSXBase.HTMLAttributes<HTMLProductTextElement>;
        }
    }
}
